[mypy]
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
no_implicit_optional = True
follow_imports = skip
disable_error_code = import-untyped

files = torax/run_simulation_main.py,torax/_src/config,torax/_src/orchestration,torax/_src/geometry/geometry.py,torax/_src/geometry/geometry_provider.py
exclude = ^docs/|^torax/tests/|^torax/examples/|^torax/_src/tests/|^torax/_src/.*/tests/|^torax/tests/test_data/
